workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

variables:
  S3_STATIC_BUCKET: python-geogebra
  PYGGB_HOSTED_BASE_PATH: python

stages:
  - build
  - release

build:
  stage: build
  tags:
    - docker
  image: node:18.16-alpine
  before_script:
    - npm clean-install
  script:
    - PUBLIC_URL=/${PYGGB_HOSTED_BASE_PATH} npm run build
  artifacts:
    paths:
      - build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

publish:
  stage: release
  script:
    - aws s3 sync ./build s3://${S3_STATIC_BUCKET}/${PYGGB_HOSTED_BASE_PATH}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH